title: "Classification Project"
author: "Name"
logo: ""
execute:
  execute_notebooks: "off"

myst_enable_extensions:
  - linkify
  - jupyter

html:
  output_folder: docs
  baseurl: /Classification_book/
  use_repository_button: true

repository:
  url: 
  path_to_book: ./
  branch: main



